version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: laravel_app
    volumes:
      - ./:/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"

    depends_on:
        - database

  database:
#    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 7b6mXCmBKgyqCtSj53JF
      MYSQL_DATABASE: lucky6
      MYSQL_USER: user
      MYSQL_PASSWORD: 7b6mXCmBKgyqCtSj53JF
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:

